sudo: false
language: python
python:
  - "3.4"
  - "3.5"
services:
  - redis-server
install:
  - pip install -U pip==8.1.1  # Locked to 8.1.1 due to pip-tools, should be ok to remote this in pip-tools>=1.7
  - pip install pip-tools
  - pip-sync requirements/development.txt
  - pip freeze
cache:
  directories:
    - $HOME/.cache/pip
    - bower_components/
before_script:
  - npm install -g bower
  - bower install
script: py.test --cov=./
after_success:
  - codecov
