---
- name: Apache uWSGI module deps
  apt: name=libapache2-mod-proxy-uwsgi
  notify:
    - restart apache
- name: Apache modules enabled
  apache2_module: state=present name={{ item }}
  with_items:
    - proxy_uwsgi
    - proxy
    - ssl
  notify:
    - restart apache
- name: Apache site
  template: dest=/etc/apache2/sites-available/socialrelay.conf src=apache.conf.j2
- name: SSL cert
  copy:
      content: "{{ ssl_cert }}"
      dest: /etc/ssl/certs/{{ socialrelay_hostname }}.crt
- name: SSL key
  copy:
      content: "{{ ssl_key }}"
      dest: /etc/ssl/private/{{ socialrelay_hostname }}.key
- name: SSL chain
  copy:
      content: "{{ ssl_chain }}"
      dest: /etc/ssl/certs/{{ socialrelay_hostname }}.chain.pem
- name: Enable site
  command: a2ensite socialrelay
  notify:
    - restart apache
