---
- name: Virtualenv
  apt: name={{ item }}
  with_items:
    - python-virtualenv
    - python3-setuptools
- name: Create virtualenv
  # We do this here since Ansible only has virtualenv_python in 2.x
  become_user: socialrelay
  command: creates=/home/socialrelay/venv virtualenv -p python3.4 /home/socialrelay/venv
- name: Update pip
  # Lock to 8.1.1 due to pip-tools, remove once pip-tools releases 1.7
  pip: name=pip state=present version=8.1.1 virtualenv=/home/socialrelay/venv
  become_user: socialrelay
- name: Install pip-tools
  pip: name=pip-tools state=latest virtualenv=/home/socialrelay/venv
  become_user: socialrelay
